# Generated by Django 4.0.5 on 2022-06-27 17:31

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor.fields.RichTextField(verbose_name='Escriba aqui su articulo'),
        ),
    ]
